---
#
# Ansible managed
#
repository:
  description: Install and configure gitlab-runner on your system.
  homepage: https://buluma.github.io/
  topics: gitlabrunner, development, ansible, molecule, playbook
